language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

matrix:
  include:
    - python: "2.7"
      env: TOXENV=docs

    - python: "2.7"
      env: TOXENV=pep8

    - python: "2.7"
      env: TOXENV=py3pep8

    # Move to the python declaration above once Travis supports Python 3.4
    - python: "2.7"
      env: TOXENV=py34

before_install:
  - "[ -d ~/.distlib ] && sudo chown -R travis:travis ~/.distlib || true"

install:
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo add-apt-repository -y ppa:pypy/ppa; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo apt-get -y update && sudo apt-get -y install pypy; fi"
  # This is required because we need to get rid of the Travis installed PyPy
  # or it'll take precedence over the PPA installed one.
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo rm -rf /usr/local/pypy/bin; fi"
  # This is required because otherwise we get a really slow PyPy
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then deactivate; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo pip install --upgrade setuptools tox; fi"
  - "if [[ $TOXENV == 'py34' ]]; then .travis/py34.sh; fi"
  - sudo apt-get install subversion bzr mercurial
  - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
  - git config --global user.email "python-virtualenv@googlegroups.com"
  - git config --global user.name "Pip"
  - pip install --upgrade setuptools
  - pip install tox

script: .travis/run.py

branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
    - 1.5.X

notifications:
  irc: "irc.freenode.org#pip"
