language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
before_install:
    - sudo apt-get install subversion bzr mercurial
    - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
    - git config --global user.email "python-virtualenv@googlegroups.com"
    - git config --global user.name "Pip"
install:
  - pip install --upgrade setuptools
  - pip install pytest pytest-xdist git+https://github.com/pypa/virtualenv@develop#egg=virtualenv scripttest>=1.3 mock
# Using -n 8because multiprocessing says a travis box has 16 CPUs (8 is half)
script: py.test -n 8
notifications:
  irc: "irc.freenode.org#pip"
branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
env:
  - PYTHONHASHSEED=0
