[tool.towncrier]
package = "pip"
filename = "NEWS.rst"
directory = "news/"
title_format = """
{version} ({project_date})
==================
"""
template = "news/_template.rst"

  [[tool.towncrier.type]]
  directory = "removal"
  name = "Removal"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "bugfix"
  name = "Bug Fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "doc"
  name = "Improved Documentation"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "trivial"
  name = "Trivial Changes"
  showcontent = false
